DND_App.Web/Controllers/AccountsController.cs
using DND_App.Web.Data;
using DND_App.Web.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DND_App.Web.Controllers
{
    public class AccountsController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        public AccountsController(UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel registerViewModel)
        {
            if (ModelState.IsValid)
            {
                // Create the user in the `AspNetUsers` table (DND_UserAuth_Db)
                var identityUser = new IdentityUser
                {
                    UserName = registerViewModel.Username,
                    Email = registerViewModel.Email
                };

                var identityResult = await userManager.CreateAsync(identityUser, registerViewModel.Password);

                if (identityResult.Succeeded)
                {
                    // Assign the "User" role
                    var roleIdentityResult = await userManager.AddToRoleAsync(identityUser, "User");

                    if (roleIdentityResult.Succeeded)
                    {
                        // Insert user into `IdentityUser<Guid>` table in `DND_Db`
                        using (var scope = HttpContext.RequestServices.CreateScope())
                        {
                                var dndDbContext =              scope.ServiceProvider.GetRequiredService<DnDDbContext>();

                            var guidUser = new IdentityUser<Guid>
                            {
                                Id = Guid.Parse(identityUser.Id),
                                UserName = identityUser.UserName,
                                NormalizedUserName = identityUser.NormalizedUserName,
                                Email = identityUser.Email,
                                NormalizedEmail = identityUser.NormalizedEmail,
                                PasswordHash = identityUser.PasswordHash,
                                SecurityStamp = identityUser.SecurityStamp,
                                ConcurrencyStamp = identityUser.ConcurrencyStamp
                            };

                            dndDbContext.Set<IdentityUser<Guid>>().Add(guidUser);
                            await dndDbContext.SaveChangesAsync();
                        }

                        // Sign in the user
                        await signInManager.SignInAsync(identityUser, isPersistent: false);
                        // Redirect to home page after successful registration
                        return RedirectToAction("Index", "Home");
                    }

                    foreach (var error in roleIdentityResult.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
                else
                {
                    foreach (var error in identityResult.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }

            // Return the view with errors if registration fails
            return View(registerViewModel);
        }


        [HttpGet]
        public IActionResult Login(string ReturnUrl)
        {
            var model = new LoginViewModel
            {
                ReturnUrl = ReturnUrl
            };

            
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel loginViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var signInResult = await signInManager.PasswordSignInAsync(
                loginViewModel.Username,
                loginViewModel.Password,
                false,
                false);

            //var user = await signInManager.UserManager.FindByNameAsync(loginViewModel.Username);
            //if (user != null)
            //{
            //    var roles = await signInManager.UserManager.GetRolesAsync(user);
            //    Console.WriteLine($"Roles for user {user.UserName}: {string.Join(", ", roles)}");
            //}
            //else
            //{
            //    Console.WriteLine("User not found.");
            //}

            if (signInResult != null && signInResult.Succeeded)
            {
                var user = await userManager.FindByNameAsync(loginViewModel.Username);
                if (user != null)
                {
                    await signInManager.RefreshSignInAsync(user);
                }

                if (!string.IsNullOrWhiteSpace(loginViewModel.ReturnUrl))
                {
                    return Redirect(loginViewModel.ReturnUrl);
                }
                return RedirectToAction("Index", "Home");
            }

            
            //Show errors
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();

            return RedirectToAction("Index", "Home");
        }
        [HttpGet]
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

DND_App.Web/Controllers/CharacterClassController.cs
using DND_App.Web.Repository;
using Microsoft.AspNetCore.Mvc;

namespace DND_App.Web.Controllers
{
    public class CharacterClassController : Controller
    {
        private readonly ICharacterClassRepository characterClassRepository;

        public CharacterClassController(ICharacterClassRepository characterClassRepository)
        {
            this.characterClassRepository = characterClassRepository;
        }

        [HttpGet]
        public async Task<IActionResult> ClassDetails(int id)
        {
            try
            {
                var characterClass = await characterClassRepository.GetClassByIdAsync(id);
                return View(characterClass);
            }
            catch (ArgumentException)
            {
                return NotFound(); // Handle invalid ID
            }
        }


        [HttpGet]
        public async Task<IActionResult> GetAllClasses()
        {
            var allClasses = await characterClassRepository.GetAllClassesAsync();
            return View(allClasses);
        }
    }
}

DND_App.Web/Controllers/CharacterController.cs
using DND_App.Web.Data;
using DND_App.Web.Models.Domain;
using DND_App.Web.Repository;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using DND_App.Web.Models.ViewModels;
using Ganss.Xss;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Text.RegularExpressions;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Constants = DND_App.Web.StaticClasses.Constants;
using DND_App.Web.StaticClasses;
using DND_App.Web.StaticClasses.Constants;
using DND_App.Web.Services;

namespace DND_App.Web.Controllers
{
    public class CharacterController : Controller
    {
        private readonly ICharacterService characterService;
        private readonly UserManager<IdentityUser> userManager;
        private readonly DnDDbContext dndDbContext;

        public CharacterController(ICharacterService characterService, UserManager<IdentityUser> userManager, DnDDbContext dndDbContext)
        {
            this.characterService = characterService;
            this.userManager = userManager;
            this.dndDbContext = dndDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var viewModel = await characterService.GetCreateCharacterViewModelAsync();
            await characterService.LoadViewBagDataAsync(ViewData);
            return View(viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateCharacterViewModel createCharacterViewModel)
        {
            if (!ModelState.IsValid)
            {
                foreach (var error in ModelState)
                {
                    Console.WriteLine($"Key: {error.Key}, Error: {string.Join(", ", error.Value.Errors.Select(e => e.ErrorMessage))}");
                }

                await characterService.LoadViewBagDataAsync(ViewData);
                return View(createCharacterViewModel);
            }

            var loggedInUser = await userManager.GetUserAsync(User);
            if (loggedInUser == null)
            {
                return RedirectToAction("Login", "Accounts");
            }

            var character = await characterService.CreateCharacterAsync(createCharacterViewModel, loggedInUser);

            if (character == null)
            {
                ModelState.AddModelError("", "An error occurred while creating the character.");
                await characterService.LoadViewBagDataAsync(ViewData);
                return View(createCharacterViewModel);
            }

            return RedirectToAction("Details", new { id = character.Id });
        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var character = await characterService.GetCharacterByIdAsync(id);
            if (character == null) return NotFound();

            await characterService.LoadViewBagDataAsync(ViewData);

            return View(character);
        }
        [HttpGet]
        public async Task<IActionResult> ReadAll()
        {
            var characters = await characterService.GetAllCharactersAsync();
            return View(characters);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var characterViewModel = await characterService.GetCharacterForEditAsync(id);
            if (characterViewModel == null)
            {
                return NotFound();
            }
            await characterService.LoadViewBagDataAsync(ViewData);

            return View(characterViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditCharacterViewModel editCharacterRequest)
        {
            if (!ModelState.IsValid)
            {
                await characterService.LoadViewBagDataAsync(ViewData);
                return View(editCharacterRequest);
            }

            var updatedCharacter = await characterService.UpdateCharacterAsync(id, editCharacterRequest);
            if (updatedCharacter == null)
            {
                return NotFound();
            }

            return RedirectToAction("Details", new { id = updatedCharacter.Id });
        }
        [HttpPost]
        [Route("Character/Delete")]
        public async Task<IActionResult> Delete(EditCharacterViewModel editCharacterViewModel)
        {
            var deletedCharacter = await characterService.DeleteCharacterAsync(editCharacterViewModel.Id);
            if (deletedCharacter)
            {
                return RedirectToAction("UserCharacters");
            }

            return RedirectToAction("Edit", new { id = editCharacterViewModel.Id });
        }
        [HttpGet]
        public async Task<IActionResult> UserCharacters()
        {
            var user = await userManager.GetUserAsync(User);
            if (user == null)
            {
                TempData["ErrorMessage"] = "You must be logged in to view your characters.";
                return RedirectToAction("Login", "Accounts");
            }

            var userCharacters = await characterService.GetUserCharactersAsync(user.Id);
            return View(userCharacters);
        }
    }
    #region Old Code
    //[HttpGet]
    //public IActionResult Create()
    //{
    //    // Pass classes and races to the view
    //    ViewBag.Classes = dndDbContext.CharacterClasses.ToList();
    //    ViewBag.Races = dndDbContext.CharacterRaces.ToList();

    //    ViewBag.Alignments = HelperMethods.GetAlignments();
    //    ViewBag.Gender = HelperMethods.GetGender();

    //    // Fetch available skills
    //    var skills = dndDbContext.Skills.ToList();
    //    ViewBag.Skills = skills;

    //    // Fetch available spells
    //    var spells = dndDbContext.Spells.ToList();
    //    ViewBag.Spells = spells;

    //    // Fetch available items
    //    var items = dndDbContext.Items.ToList();
    //    ViewBag.Items = items;

    //    // Fetch available treasures
    //    var treasures = dndDbContext.Treasures.ToList();
    //    ViewBag.Treasures = treasures;

    //    // Create a CreateCharacterViewModel with initial values
    //    var characterViewModel = new CreateCharacterViewModel
    //    {
    //        // Initialize CharacterSkills
    //        CharacterSkills = skills.Select(s => new CharacterSkillRequest
    //        {
    //            SkillId = s.Id,
    //            IsProficient = false,
    //            Bonus = 0
    //        }).ToList(),

    //        // Initialize CharacterSpells
    //        CharacterSpells = spells.Select(sp => new CharacterSpellRequest
    //        {
    //            SpellId = sp.Id,
    //            IsLearned = false 
    //        }).ToList(),

    //        // Initialize ItemName
    //        CharacterItems = items.Select(ci => new CharacterItemRequest
    //        {
    //            ItemId = ci.Id,
    //            Quantity = 0
    //        }).ToList(),

    //        // Initialize CharacterTreasures
    //        CharacterTreasures = treasures.Select(ct => new CharacterTreasureRequest
    //        {
    //            TreasureId = ct.Id,
    //            Quantity = 0
    //        }).ToList()
    //    };

    //    return View(characterViewModel);
    //}

    //[HttpPost]
    //public async Task<IActionResult> Create(CreateCharacterViewModel createCharacterViewModel)
    //{
    //    // Check if the form submission is valid
    //    if (!ModelState.IsValid)
    //    {
    //        foreach (var error in ModelState)
    //        {
    //            Console.WriteLine($"Key: {error.Key}, Error: {string.Join(", ", error.Value.Errors.Select(e => e.ErrorMessage))}");
    //        }

    //        await LoadViewBagData();
    //        return View(createCharacterViewModel);
    //    }

    //    // Get the currently logged-in loggedInUser
    //    var loggedInUser = await userManager.GetUserAsync(User);

    //    // Sanitize the CharacterBackstory to prevent malicious input
    //    var sanitizer = new HtmlSanitizer();
    //    createCharacterViewModel.CharacterBackstory = sanitizer.Sanitize(createCharacterViewModel.CharacterBackstory);

    //    // Fetch the selected CharacterClass from the database
    //    var characterClass = await dndDbContext.CharacterClasses
    //        .FirstOrDefaultAsync(c => c.Id == createCharacterViewModel.CharacterClassId);

    //    if (characterClass == null)
    //    {
    //        ModelState.AddModelError("", "Invalid character class selected.");
    //        await LoadViewBagData();
    //        return View(createCharacterViewModel);
    //    }

    //    // Filter and map items from the ViewModel before adding to the domain model
    //    var characterItems = createCharacterViewModel.CharacterItems
    //        .Where(ci => ci.Quantity > 0) // Only save items with quantity > 0
    //        .Select(ci => new CharacterItem
    //        {
    //            ItemId = ci.ItemId,
    //            Quantity = ci.Quantity
    //        }).ToList();


    //    // Map the CreateCharacterViewModel to a new Character entity
    //    var characterDomainModel = new Character
    //    {
    //        // User-related properties
    //        UserId = Guid.Parse(loggedInUser.Id), 
    //        PlayerName = loggedInUser.UserName,

    //        CharacterName = createCharacterViewModel.CharacterName,
    //        CharacterClassId = createCharacterViewModel.CharacterClassId,
    //        CharacterClass = characterClass,
    //        CharacterRaceId = createCharacterViewModel.CharacterRaceId,
    //        Strength = createCharacterViewModel.Strength,
    //        Dexterity = createCharacterViewModel.Dexterity,
    //        Constitution = createCharacterViewModel.Constitution,
    //        Intelligence = createCharacterViewModel.Intelligence,
    //        Wisdom = createCharacterViewModel.Wisdom,

DND_App.Web/Controllers/CharacterRaceController.cs
using DND_App.Web.Repository;
using Microsoft.AspNetCore.Mvc;

namespace DND_App.Web.Controllers
{
    public class CharacterRaceController : Controller
    {
        private readonly ICharacterRaceRepository characterRaceRepository;

        public CharacterRaceController(ICharacterRaceRepository characterRaceRepository)
        {
            this.characterRaceRepository = characterRaceRepository;
        }

        [HttpGet]
        public async Task<IActionResult> RaceDetails(int id)
        {
            var race = await characterRaceRepository.GetRaceByIdAsync(id);
            return View(race);
        }
        [HttpGet]
        public async Task<IActionResult> GetAllRaces()
        {
            var races = await characterRaceRepository.GetAllRacesAsync();
            return View(races);
        }
    }
}

DND_App.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>D&D Character Creator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">


    @*<link rel="stylesheet" href="~/css/DNDApp.Web.styles.css" asp-append-version="true" />*@

    <link href='https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">

    <!-- Bootstrap JS (requires Popper.js for interactivity) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.min.js"></script>

    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js'></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</head>
<body class="@ViewData["BodyClass"] d-flex flex-column min-vh-100">
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-dark text-light">
            <div class="container-fluid">
                <a class="navbar-brand text-white"
                   asp-area=""
                   asp-controller="Home"
                   asp-action="Index">
                    D&D Character Creator
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white"
                               asp-area=""
                               asp-controller="Home"
                               asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"
                               asp-area=""
                               asp-controller="CharacterClass"
                               asp-action="GetAllClasses">View Classes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"
                               asp-area=""
                               asp-controller="CharacterRace"
                               asp-action="GetAllRaces">View Races</a>
                        </li>
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white"
                                   asp-area=""
                                   asp-controller="Character"
                                   asp-action="Create">
                                    Create Character
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white"
                                   asp-controller="Character"
                                   asp-action="UserCharacters">
                                    Your Characters
                                </a>
                            </li>
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link text-white dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                                        Admin
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a class="dropdown-item"
                                               asp-area=""
                                               asp-controller="AdminUser"
                                               asp-action="List">
                                                Users
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item"
                                               asp-area=""
                                               asp-controller="Character"
                                               asp-action="ReadAll">
                                                Characters
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item"
                                               asp-area=""
                                               asp-controller="AdminUser"
                                               asp-action="CreateRace">
                                                Add Race Images
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            }
                        }
                    </ul>
                    <div class="d-flex align-items-center">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <span class="me-3 text-light">@User.Identity.Name</span>
                            <a class="btn btn-danger btn-sm"
                               asp-area=""
                               asp-controller="Accounts"
                               asp-action="Logout">Logout</a>
                        }
                        else
                        {
                            <a class="btn btn-success btn-sm me-2"
                               asp-area=""
                               asp-controller="Accounts"
                               asp-action="Login">Login</a>
                            <a class="btn btn-primary btn-sm"
                               asp-area="" asp-controller="Accounts"
                               asp-action="Register">Register</a>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="flex-grow-1">
        @RenderBody()
    </main>

    <footer class="bg-dark text-light text-center py-3 mt-auto">
        <div class="container">
            &copy; 2025 - DND_App.Web -
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

@*Real-time validation feedback*@
@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
}